#!/bin/bash
# Filter the JSON output
export region=us-east-2
aws ec2 describe-instances --region ${region} |  \
  jq -c '( .Reservations[].Instances[] | [ .InstanceType, .InstanceId, .InstanceLifecycle, .State["Name"] ])' | \
  grep -E -v 'terminated|stopped'
