#!/bin/bash
# Filter the JSON output
aws ec2 describe-instances |  \
  jq -c '( .Reservations[].Instances[] | [ .InstanceType, .InstanceId, .InstanceLifecycle, .State["Name"] ])' | \
  grep -E -v 'terminated|stopped'
