#!/bin/bash
export region="us-east-2"
cmd="aws ec2 run-instances --region $region --launch-template LaunchTemplateName=TemplateForSpot,Version=1 --instance-market-options MarketType=spot"
echo "running\n$cmd"
$cmd
