#!/bin/bash
aws ec2 create-fleet \
   --launch-template-configs LaunchTemplateSpecification="{LaunchTemplateName=TemplateForSpot,Version=1}" \
   --target-capacity-specification TotalTargetCapacity=3,OnDemandTargetCapacity=1,DefaultTargetCapacityType=spot
