#!/bin/bash
export region="us-east-2"
aws ec2 create-fleet --region $region \
   --launch-template-configs LaunchTemplateSpecification="{LaunchTemplateName=TemplateForSpot,Version=1}" \
   --target-capacity-specification TotalTargetCapacity=4,OnDemandTargetCapacity=1,DefaultTargetCapacityType=spot \
   --type request
